def get_countries():
    return [
        "ACORES",
        "AFGHANISTAN",
        "ALBANIA",
        "ALGERIA",
        "ANGOLA",
        "ANGUILLA ISL.",
        "ANTARCTICA",
        "ANTILLES",
        "ARGENTINA",
        "ARUBA",
        "AUSTRALIA",
        "AUSTRIA",
        "BAHAMAS",
        "BAHRAIN",
        "BANGLADESH",
        "BARBADOS",
        "BELGIUM",
        "BELIZE",
        "BENIN",
        "BHUTAN",
        "BOLIVIA",
        "BOPHUTHATSWANA",
        "BOSNIA-HERCEGOVINA",
        "BOTSWANA",
        "BRASIL",
        "BRUNEI",
        "BULGARIA",
        "BURKINA FASO",
        "BURUNDI",
        "CAMBODIA",
        "CAMEROON",
        "CANADA",
        "CANARY ISLANDS",
        "CAPE VERDE ISLANDS",
        "CAYMAN ISLANDS",
        "CENTRAL AFRICAN REP.",
        "CHAD",
        "CHILE",
        "CHINA",
        "CHRISTMAS ISLAND",
        "COLOMBIA",
        "COMOROS ISLANDS",
        "CONGO",
        "COOK ISLANDS",
        "CORSE ISL.",
        "COSTA RICA",
        "CROATIA",
        "CUBA",
        "CYPRUS",
        "CZECH REPUBLIC",
        "DENMARK",
        "DIEGO GARCIA ISLAND",
        "DOMINICA",
        "DOMINICAN REPUBLIC",
        "EAST TIMOR",
        "ECUADOR",
        "EGYPT",
        "EL SALVADOR",
        "ENGALND",
        "ENGLAND",
        "EQUATORIAL GUINEA",
        "ESTONIA",
        "ETHIOPIA",
        "FALKLAND ISLANDS",
        "FAROE ISL.",
        "FIJI",
        "FINLAND",
        "FORMER MACEDONIA",
        "FRANCE",
        "FRENCH GUYANA",
        "FRENCH POLYNESIA",
        "GABON",
        "GALAPAGOS I. (ECUADOR",
        "GAMBIA",
        "GEORGIA",
        "GERMANY",
        "GHANA",
        "GIBRALTAR",
        "GREECE",
        "GREENLAND",
        "GRENADA",
        "GUATEMALA",
        "GUERNSEY ISLD.",
        "GUINEA",
        "GUINEA BISSAU",
        "GUYANA",
        "HAITI",
        "HONDURAS",
        "HONG KONG",
        "HUNGARY",
        "ICELAND",
        "INDIA",
        "INDONESIA",
        "IRAN",
        "IRAQ",
        "IRELAND",
        "ISRAEL",
        "ITALY",
        "IVORY COAST",
        "JAMAICA",
        "JAPAN",
        "JOHNSTON ATOLL",
        "JORDAN",
        "KAZAKHSTAN",
        "KENYA",
        "KIRIBATI",
        "KOREA",
        "KUWAIT",
        "LAOS",
        "LEBANON",
        "LEEWARD ISLANDS",
        "LESOTHO",
        "LIBERIA",
        "LIBYA",
        "LUXEMBURG",
        "MACAU",
        "MADAGASCAR",
        "MADEIRA",
        "MALAWI",
        "MALAYSIA",
        "MALDIVES",
        "MALI",
        "MALTA",
        "MARIANA ISLANDS",
        "MARSHALL ISLANDS",
        "MAURITANIA",
        "MAURITIUS",
        "MAYOTTE ISLAND",
        "MEXICO",
        "MICRONESIA",
        "MIDWAY ISLAND",
        "MOLDOVA",
        "MONGOLIA",
        "MONTSERRAT ISLAND",
        "MOROCCO",
        "MOZAMBIQUE",
        "MYANMAR",
        "NEPAL",
        "NETHERLANDS",
        "NEW CALEDONIA",
        "NEW ZEALAND",
        "NICARAGUA",
        "NIGER",
        "NIGERIA",
        "NORTH IRELAND",
        "NORWAY",
        "OMAN",
        "PAKISTAN",
        "PALAU ISLAND",
        "PANAMA",
        "PAPUA NEW GUINEA",
        "PARAGUAY",
        "PERU",
        "PHILIPPINES",
        "PHOENIX ISL.",
        "POLAND",
        "PORTUGAL",
        "PUERTO RICO",
        "QATAR",
        "REUNION ISLAND",
        "ROMANIA",
        "RUSSIA",
        "RWANDA",
        "SAMOA",
        "SAO TOME & PRINCIPE",
        "SAUDI ARABIA",
        "SCOTLAND",
        "SENEGAL",
        "SEYCHELLES",
        "SIERRA LEONE",
        "SINGAPORE",
        "SLOVAKIA",
        "SLOVENIA",
        "SOMALIA",
        "SOUTH AFRICA",
        "SPAIN",
        "SPANISH NORTH AFRICA",
        "SRI LANKA",
        "ST. KITTS & NEVIS",
        "ST. LUCIA ISLAND",
        "ST. PIERRE & MIQUELON",
        "ST.VINCENT/GRENADINES",
        "SUDAN",
        "SURINAM",
        "SWAZILAND",
        "SWEDEN",
        "SWITZERLAND",
        "SYRIA",
        "TAIWAN",
        "TANZANIA",
        "THAILAND",
        "TOGO",
        "TONGA",
        "TRINIDAD & TOBAGO",
        "TUAMOTU ISLANDS",
        "TUNISIA",
        "TURKEY",
        "TURKS & CAICOS I.",
        "TUVALU ISLAND",
        "UGANDA",
        "U.K",
        "U.K.",
        "UNITED ARAB EMIRATES",
        "URUGUAY",
        "USA",
        "USA (FLORIDA)",
        "USA HAWAII ISL.",
        "USA KAUAI ISL.",
        "USA LANAI ISL.",
        "USA MAUI ISL.",
        "USA MOLOKAI ISL.",
        "USA OAHU ISL.",
        "UZBEKISTAN",
        "VANUATU",
        "VENEZUELA",
        "VIET NAM",
        "VIRGIN ISL.",
        "WALES",
        "WALLIS & FUTUNA",
        "WEST TIMOR",
        "YUGOSLAVIA",
        "ZAIRE",
        "ZAMBIA",
        "ZIMBABWE",
    ]
